import './globals.css'
import { Inter } from 'next/font/google'
import App from '../components/App/App'
import StyledJsxRegistry from './registry'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Job post',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledJsxRegistry>
          <App>{children}</App>
        </StyledJsxRegistry>
      </body>
    </html>
  )
}
